/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'jcooper' at '1/16/16 8:37 PM' with Gradle 2.9
 *
 * @author jcooper, @date 1/16/16 8:37 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
